<?php
/**
 * Created by PhpStorm.
 * User: ddiallo
 * Date: 9/6/19
 * Time: 2:39 PM
 */

use Drupal\node\Entity\Node;
use Drupal\indicators_generator\Util\IndicatorsGenUtility;

/**
 * Implements hook_node_presave
 */

function indicators_generator_node_presave(Drupal\node\NodeInterface $node) {

  //For Old test for this

  if ($node->bundle() == "tajikistan_data_entry") {


    //Dont't need to enter if empty will use insert for to catch id
    if ($node->id()) { //Nouveau et ancien convoquer

      $terms = new IndicatorsGenUtility();

      $title = $terms->getTermName($node->get('field_state_province')
          ->getValue()[0]["target_id"]) . "-" . $terms->getTermName($node->get('field_year')
          ->getValue()[0]["target_id"]) . "-" . $terms->getTermName($node->get('field_period')
          ->getValue()[0]["target_id"]) . "-Indicators";

      $entity = \Drupal::entityTypeManager()
        ->getStorage('basic_data');

      $my_taji_ind = $entity->loadByProperties(['name' => $title]);

      if (!empty($my_taji_ind)) {
        $entity->delete($my_taji_ind);
      }
      $entity_definition = \Drupal::entityTypeManager()
        ->getDefinition('basic_data');
      $values = [
        $entity_definition->getKey('bundle') => 'tajikistan_indicators',
        'name' => $title,
        'data' => 'Somme data',
        'field_taji_data_year' => $terms->getTermName($node->get('field_year')
          ->getValue()[0]["target_id"]),
        'field_taji_data_period' => $terms->getTermName($node->get('field_period')
          ->getValue()[0]["target_id"]),
        'field_taji_data_province_state' => $terms->getTermName($node->get('field_state_province')
          ->getValue()[0]["target_id"]),
        'field_taji_data_district' => $terms->getTermName($node->get('field_district')
          ->getValue()[0]["target_id"]),
        'field_estimated_number_of_incide' => $node->get('field_e_inc_num')
          ->getValue()[0]["value"],
        'field_proportion_of_estimated_ca' => (is_null($node->get('field_e_inc_num')
            ->getValue()[0]["value"]) || $node->get('field_e_inc_num')
            ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_c_newinc')
            ->getValue()[0]["value"] / $node->get('field_e_inc_num')
            ->getValue()[0]["value"],
        'field_new_pulmonary_bacteriologi' => (is_null($node->get('field_c_newinc')
            ->getValue()[0]["value"]) || $node->get('field_c_newinc')
            ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_new_labconf')
            ->getValue()[0]["value"] + $node->get('field_new_ep')
            ->getValue()[0]["value"] / $node->get('field_c_newinc')
            ->getValue()[0]["value"],
        'field_proportion_of_rr_mdr_tb_ca' => (is_null($node->get('field_mdr_coh')
            ->getValue()[0]["value"]) || $node->get('field_mdr_coh')
            ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_mdr_succ')
            ->getValue()[0]["value"] / $node->get('field_mdr_coh')
            ->getValue()[0]["value"],
        'field_proportion_of_new_pulmonar' => (is_null($node->get('field_newrel_coh')
            ->getValue()[0]["value"]) || $node->get('field_newrel_coh')
            ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_newrel_succ')
            ->getValue()[0]["value"] / $node->get('field_newrel_coh')
            ->getValue()[0]["value"],
        'field_estimated_incidence_of_rif' => $node->get('field_e_inc_rr_num')
          ->getValue()[0]["value"],
        'field_number_of_new_and_relapse‎' => (is_null($node->get('field_conf_rrmdr')
            ->getValue()[0]["value"]) || $node->get('field_conf_rrmdr')
            ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_all_conf_xdr')
            ->getValue()[0]["value"] / $node->get('field_conf_rrmdr')
            ->getValue()[0]["value"],
        'field_proportion_of_xdr_tb_cases‎' => (is_null($node->get('field_xdr_coh')
            ->getValue()[0]["value"]) || $node->get('field_xdr_coh')
            ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_xdr_succ')
            ->getValue()[0]["value"] / $node->get('field_xdr_coh')
            ->getValue()[0]["value"],
        'field_relationship' => $node->id(),
      ];
      $entity->create($values)->save();


      /**
       * When using node to store indicators
       */
      //      $my_article = \Drupal::entityTypeManager()
      //        ->getStorage('node')
      //        ->loadByProperties(['title' => $title]);
      //      //Test before create
      //      if (empty($my_article)) {
      //        $my_article = Node::create(['type' => 'tajikistan_indicators']);
      //        $my_article->set('title', $title);
      //        $status = TRUE;
      //      }

      //
      //      $my_article->set('field_taji_ind_year', $terms->getTermName($node->get('field_year')
      //        ->getValue()[0]["target_id"]));
      //      $my_article->set('field_taji_ind_period', $terms->getTermName($node->get('field_period')
      //        ->getValue()[0]["target_id"]));
      //      $my_article->set('field_taji_ind_state_province', $terms->getTermName($node->get('field_state_province')
      //        ->getValue()[0]["target_id"]));
      //      $my_article->set('field_taji_ind_district', $terms->getTermName($node->get('field_district')
      //        ->getValue()[0]["target_id"]));
      //      $my_article->set('field_estimated_number_of_incide', $node->get('field_e_inc_num')
      //        ->getValue()[0]["value"]);
      //      $my_article->set('field_proportion_of_estimated_ca', (is_null($node->get('field_e_inc_num')
      //          ->getValue()[0]["value"]) || $node->get('field_e_inc_num')
      //          ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_c_newinc')
      //          ->getValue()[0]["value"] / $node->get('field_e_inc_num')
      //          ->getValue()[0]["value"]);
      //      $my_article->set('field_new_pulmonary_bacteriologi', (is_null($node->get('field_c_newinc')
      //          ->getValue()[0]["value"]) || $node->get('field_c_newinc')
      //          ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_new_labconf')
      //          ->getValue()[0]["value"] + $node->get('field_new_ep')
      //          ->getValue()[0]["value"] / $node->get('field_c_newinc')
      //          ->getValue()[0]["value"]);
      //      $my_article->set('field_proportion_of_rr_mdr_tb_ca', (is_null($node->get('field_mdr_coh')
      //          ->getValue()[0]["value"]) || $node->get('field_mdr_coh')
      //          ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_mdr_succ')
      //          ->getValue()[0]["value"] / $node->get('field_mdr_coh')
      //          ->getValue()[0]["value"]);
      //      $my_article->set('field_proportion_of_new_pulmonar', (is_null($node->get('field_newrel_coh')
      //          ->getValue()[0]["value"]) || $node->get('field_newrel_coh')
      //          ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_newrel_succ')
      //          ->getValue()[0]["value"] / $node->get('field_newrel_coh')
      //          ->getValue()[0]["value"]);
      //      $my_article->set('field_estimated_incidence_of_ri', $node->get('field_e_inc_rr_num')
      //        ->getValue()[0]["value"]);
      ////      $my_article->set('field_number_of_new_and_relapse‎', (is_null($node->get('field_conf_rrmdr')
      ////          ->getValue()[0]["value"]) || $node->get('field_conf_rrmdr')
      ////          ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_all_conf_xdr')
      ////          ->getValue()[0]["value"] / $node->get('field_conf_rrmdr')
      ////          ->getValue()[0]["value"]);
      ////      $my_article->set('field_proportion_of_xdr_tb_cases‎', (is_null($node->get('field_xdr_coh')
      ////          ->getValue()[0]["value"]) || $node->get('field_xdr_coh')
      ////          ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_xdr_succ')
      ////          ->getValue()[0]["value"] / $node->get('field_xdr_coh')
      ////          ->getValue()[0]["value"]);
      //      $my_article->set('field_relationship', $node->id());
      //      if ($status) {
      //        $my_article->enforceIsNew();
      //      }
      //      $my_article->save();
    }
  }
}

/**
 * Implement hook_node_insert
 *
 * @param \Drupal\node\NodeInterface $node
 */

function indicators_generator_node_insert(Drupal\node\NodeInterface $node) {
  //FOR NEW
  //PUT HERE FOR NEW AND ABOVE FOR OLD
  if ($node->bundle() == "tajikistan_data_entry") {

    //Test just the value since it's not null in this level
    if ($node->id()) {

      $terms = new IndicatorsGenUtility();

      $title = $terms->getTermName($node->get('field_state_province')
          ->getValue()[0]["target_id"]) . "-" . $terms->getTermName($node->get('field_year')
          ->getValue()[0]["target_id"]) . "-" . $terms->getTermName($node->get('field_period')
          ->getValue()[0]["target_id"]) . "-Indicators";

      $entity = \Drupal::entityTypeManager()
        ->getStorage('basic_data');

      $my_taji_ind = $entity->loadByProperties(['name' => $title]);

      if (!empty($my_taji_ind)) {
        $entity->delete($my_taji_ind);
      }
      $entity_definition = \Drupal::entityTypeManager()
        ->getDefinition('basic_data');
      $values = [
        $entity_definition->getKey('bundle') => 'tajikistan_indicators',
        'name' => $title,
        'data' => 'Somme data',
        'field_taji_data_year' => $terms->getTermName($node->get('field_year')
          ->getValue()[0]["target_id"]),
        'field_taji_data_period' => $terms->getTermName($node->get('field_period')
          ->getValue()[0]["target_id"]),
        'field_taji_data_province_state' => $terms->getTermName($node->get('field_state_province')
          ->getValue()[0]["target_id"]),
        'field_taji_data_district' => $terms->getTermName($node->get('field_district')
          ->getValue()[0]["target_id"]),
        'field_estimated_number_of_incide' => $node->get('field_e_inc_num')
          ->getValue()[0]["value"],
        'field_proportion_of_estimated_ca' => (is_null($node->get('field_e_inc_num')
            ->getValue()[0]["value"]) || $node->get('field_e_inc_num')
            ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_c_newinc')
            ->getValue()[0]["value"] / $node->get('field_e_inc_num')
            ->getValue()[0]["value"],
        'field_new_pulmonary_bacteriologi' => (is_null($node->get('field_c_newinc')
            ->getValue()[0]["value"]) || $node->get('field_c_newinc')
            ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_new_labconf')
            ->getValue()[0]["value"] + $node->get('field_new_ep')
            ->getValue()[0]["value"] / $node->get('field_c_newinc')
            ->getValue()[0]["value"],
        'field_proportion_of_rr_mdr_tb_ca' => (is_null($node->get('field_mdr_coh')
            ->getValue()[0]["value"]) || $node->get('field_mdr_coh')
            ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_mdr_succ')
            ->getValue()[0]["value"] / $node->get('field_mdr_coh')
            ->getValue()[0]["value"],
        'field_proportion_of_new_pulmonar' => (is_null($node->get('field_newrel_coh')
            ->getValue()[0]["value"]) || $node->get('field_newrel_coh')
            ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_newrel_succ')
            ->getValue()[0]["value"] / $node->get('field_newrel_coh')
            ->getValue()[0]["value"],
        'field_estimated_incidence_of_rif' => $node->get('field_e_inc_rr_num')
          ->getValue()[0]["value"],
        'field_number_of_new_and_relapse‎' => (is_null($node->get('field_conf_rrmdr')
            ->getValue()[0]["value"]) || $node->get('field_conf_rrmdr')
            ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_all_conf_xdr')
            ->getValue()[0]["value"] / $node->get('field_conf_rrmdr')
            ->getValue()[0]["value"],
        'field_proportion_of_xdr_tb_cases‎' => (is_null($node->get('field_xdr_coh')
            ->getValue()[0]["value"]) || $node->get('field_xdr_coh')
            ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_xdr_succ')
            ->getValue()[0]["value"] / $node->get('field_xdr_coh')
            ->getValue()[0]["value"],
        'field_relationship' => $node->id(),
      ];
      $entity->create($values)->save();

      /**
       * When using node to store indicators
       */
      //      //Test if indic exist
      //      $my_article = \Drupal::entityTypeManager()
      //        ->getStorage('node')
      //        ->loadByProperties(['title' => $title]);
      //
      //      //Test before create
      //      if (empty($my_article)) {
      //        $my_article = Node::create(['type' => 'tajikistan_indicators']);
      //        $my_article->set('title', $title);
      //        $status = TRUE;
      //      }
      //
      //      //Update fields
      //      //todo manage denominator if null
      //      $my_article->set('field_taji_ind_year', $terms->getTermName($node->get('field_year')
      //        ->getValue()[0]["target_id"]));
      //      $my_article->set('field_taji_ind_period', $terms->getTermName($node->get('field_period')
      //        ->getValue()[0]["target_id"]));
      //      $my_article->set('field_taji_ind_state_province', $terms->getTermName($node->get('field_state_province')
      //        ->getValue()[0]["target_id"]));
      //      $my_article->set('field_taji_ind_district', $terms->getTermName($node->get('field_district')
      //        ->getValue()[0]["target_id"]));
      //      $my_article->set('field_estimated_number_of_incide', $node->get('field_e_inc_num')
      //        ->getValue()[0]["value"]);
      //      $my_article->set('field_proportion_of_estimated_ca', (is_null($node->get('field_e_inc_num')
      //          ->getValue()[0]["value"]) || $node->get('field_e_inc_num')
      //          ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_c_newinc')
      //          ->getValue()[0]["value"] / $node->get('field_e_inc_num')
      //          ->getValue()[0]["value"]);
      //      $my_article->set('field_new_pulmonary_bacteriologi', (is_null($node->get('field_c_newinc')
      //          ->getValue()[0]["value"]) || $node->get('field_c_newinc')
      //          ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_new_labconf')
      //          ->getValue()[0]["value"] + $node->get('field_new_ep')
      //          ->getValue()[0]["value"] / $node->get('field_c_newinc')
      //          ->getValue()[0]["value"]);
      //      $my_article->set('field_proportion_of_rr_mdr_tb_ca', (is_null($node->get('field_mdr_coh')
      //          ->getValue()[0]["value"]) || $node->get('field_mdr_coh')
      //          ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_mdr_succ')
      //          ->getValue()[0]["value"] / $node->get('field_mdr_coh')
      //          ->getValue()[0]["value"]);
      //      $my_article->set('field_proportion_of_new_pulmonar', (is_null($node->get('field_newrel_coh')
      //          ->getValue()[0]["value"]) || $node->get('field_newrel_coh')
      //          ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_newrel_succ')
      //          ->getValue()[0]["value"] / $node->get('field_newrel_coh')
      //          ->getValue()[0]["value"]);
      //      $my_article->set('field_estimated_incidence_of_ri', $node->get('field_e_inc_rr_num')
      //        ->getValue()[0]["value"]);
      ////      $my_article->set('field_number_of_new_and_relapse‎', (is_null($node->get('field_conf_rrmdr')
      ////          ->getValue()[0]["value"]) || $node->get('field_conf_rrmdr')
      ////          ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_all_conf_xdr')
      ////          ->getValue()[0]["value"] / $node->get('field_conf_rrmdr')
      ////          ->getValue()[0]["value"]);
      ////      $my_article->set('field_proportion_of_xdr_tb_cases‎', (is_null($node->get('field_xdr_coh')
      ////          ->getValue()[0]["value"]) || $node->get('field_xdr_coh')
      ////          ->getValue()[0]["value"] == 0) ? 0 : $node->get('field_xdr_succ')
      ////          ->getValue()[0]["value"] / $node->get('field_xdr_coh')
      ////          ->getValue()[0]["value"]);
      //      $my_article->set('field_relationship', $node->id());
      //      if ($status) {
      //        $my_article->enforceIsNew();
      //      }
      //      $my_article->save();
    }
  }
}
